/**
 * Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ManagerContactInfoGet200ResponseInner { 
    /**
     * ID of the contact information
     */
    id?: number;
    /**
     * Street address
     */
    street?: string;
    /**
     * City name
     */
    city?: string;
    /**
     * ZIP code
     */
    zip_code?: string;
    /**
     * Phone number
     */
    phone?: string;
    /**
     * Email address
     */
    email?: string;
    /**
     * Facebook URL
     */
    facebook_url?: string;
    /**
     * Twitter URL
     */
    twitter_url?: string;
    /**
     * Google URL
     */
    google_url?: string;
    /**
     * Instagram URL
     */
    instagram_url?: string;
}

