/**
 * Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReservationSchema { 
    day_of_week?: number;
    /**
     * Opening time in HH:MM format
     */
    opening_time?: string;
    /**
     * Closing time in HH:MM format
     */
    closing_time?: string;
    /**
     * Minimum reservation length in minutes
     */
    min_reservation_length?: number;
    /**
     * Maximum reservation length in minutes
     */
    max_reservation_length?: number;
}

