openapi: 3.0.0
info:
  title: Authentication API
  description: API for user authentication (registration and login)
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000/api 
paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './defs/auth/LoginData.yaml'
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid input
  /login:
    post:
      summary: Log in an existing user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './defs/auth/User.yaml'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: './defs/auth/LoginResponse.yaml'
        '401':
          description: Invalid credentials
  /logout:
    post:
      summary: Log out an existing user
      responses:
        '200':
          description: Logout successful
        '400':
          description: Logout invalid
  /request-password-reset:
    post:
      summary: Reset the password using email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './defs/auth/RequestResetPassword.yaml'
      responses:
        '200':
          description: Email to reset password has been sent
        '400':
          description: Cannot send email to reset password
  /reservation:
    post:
      summary: Create a new reservation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './defs/auth/Reservation.yaml'
      responses:
        '201':
          description: Reservation created successfully
        '400':
          description: Invalid input
        '409':
          description: Conflict - Table already reserved
      security:
        - bearerAuth: []
    get:
      summary: Get occupied tables for a specific date and time range
      parameters:
        - in: query
          name: reservation_start
          schema:
            type: string
            format: date-time
          required: true
          description: Start time of the time range to check (ISO format)
        - in: query
          name: reservation_end
          schema:
            type: string
            format: date-time
          required: true
          description: End time of the time range to check (ISO format)
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  occupied_table_ids:
                    type: array
                    items:
                      type: integer
        '400':
          description: Invalid input

      