/**
 * Authentication API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoginPost200Response { 
    /**
     * JWT token for authenticated sessions
     */
    token?: string;
}

