/**
 * Authentication API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoginResponse { 
    /**
     * JWT token for authenticated sessions
     */
    token: string;
    name: string;
    isAdmin: boolean;
}

