/**
 * Authentication API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResetPassword { 
    /**
     * Nowe hasło użytkownika.
     */
    newPassword: string;
    /**
     * Token resetowania hasła wysłany na e-mail.
     */
    resetToken: string;
}

