/**
 * Authentication API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Table { 
    /**
     * ID of the table
     */
    readonly id?: number;
    /**
     * Availability of the table
     */
    available?: boolean;
    /**
     * X-coordinate of the table
     */
    x: number;
    /**
     * Y-coordinate of the table
     */
    y: number;
    /**
     * Width of the table
     */
    width: number;
    /**
     * Height of the table
     */
    height: number;
    /**
     * Shape of the table
     */
    shape: string;
    /**
     * Tooltip information for the table
     */
    tooltip: string;
}

